export type Product = {
  id: number;
  name: string;
  price: number;
  tag: string;
  rating: number;
  reviews: number;
  delivery: string;
  customizable: string;
  description: string;
  sizes: string[];
  image: string;
  category: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Resin Name Plate",
    price: 799,
    tag: "Best Seller",
    rating: 4.9,
    reviews: 128,
    delivery: "3–5 days",
    customizable: "Any color",
    description:
      "A beautifully handcrafted resin name plate made entirely to order. Choose your name, preferred color palette, and size. Perfect for home décor, office desks, and gifting.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0ea?w=800&q=80",
    category: "Resin",
  },
  {
    id: 2,
    name: "Customized Photo Frame",
    price: 999,
    tag: "Popular",
    rating: 4.8,
    reviews: 95,
    delivery: "3–5 days",
    customizable: "Any photo",
    description:
      "A premium customized photo frame crafted with care. Upload your favorite memory and we'll turn it into a beautiful keepsake. Great for birthdays, anniversaries, and weddings.",
    sizes: ["4×6", "5×7", "8×10"],
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80",
    category: "Frames",
  },
  {
    id: 3,
    name: "Handmade Gift Box",
    price: 599,
    tag: "Trending",
    rating: 4.7,
    reviews: 74,
    delivery: "2–4 days",
    customizable: "Custom message",
    description:
      "A lovingly assembled handmade gift box, perfect for any occasion. Each box is uniquely decorated and can be personalized with a heartfelt message or name.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80",
    category: "Gifts",
  },
  {
    id: 4,
    name: "Decorative Candle Set",
    price: 499,
    tag: "New",
    rating: 4.6,
    reviews: 42,
    delivery: "3–5 days",
    customizable: "Scent & color",
    description:
      "A set of hand-poured decorative candles in elegant designs. Choose your preferred scent and color combination for a truly personal touch.",
    sizes: ["Set of 2", "Set of 4", "Set of 6"],
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&q=80",
    category: "Candles",
  },
  {
    id: 5,
    name: "Resin Wall Clock",
    price: 1499,
    tag: "Premium",
    rating: 4.9,
    reviews: 61,
    delivery: "5–7 days",
    customizable: "Colors & size",
    description:
      "A stunning handmade resin wall clock that doubles as wall art. Each piece is one-of-a-kind, made with premium pigments and a silent quartz movement.",
    sizes: ["10 inch", "12 inch", "14 inch"],
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80",
    category: "Resin",
  },
  {
    id: 6,
    name: "Personalized Keychain",
    price: 299,
    tag: "Hot",
    rating: 4.8,
    reviews: 210,
    delivery: "2–3 days",
    customizable: "Name & color",
    description:
      "A cute and durable personalized keychain made with premium resin. Add any name or initials and choose from a wide range of colors.",
    sizes: ["Standard"],
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
    category: "Gifts",
  },
  {
    id: 7,
    name: "Resin Serving Tray",
    price: 1299,
    tag: "Premium",
    rating: 4.9,
    reviews: 53,
    delivery: "5–7 days",
    customizable: "Colors & pattern",
    description:
      "An elegant resin serving tray that combines function and art. Each tray is handcrafted with swirling pigments, perfect for serving or as a decorative accent.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&q=80",
    category: "Resin",
  },
  {
    id: 8,
    name: "Wooden Floating Shelf",
    price: 849,
    tag: "Trending",
    rating: 4.7,
    reviews: 88,
    delivery: "4–6 days",
    customizable: "Wood finish",
    description:
      "A minimalist wooden floating shelf, handcrafted from solid wood. Ideal for displaying décor, books, or plants. Available in multiple wood finishes.",
    sizes: ["12 inch", "18 inch", "24 inch"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    category: "Home Decor",
  },
  {
    id: 9,
    name: "Pressed Flower Bookmark Set",
    price: 349,
    tag: "New",
    rating: 4.6,
    reviews: 39,
    delivery: "2–4 days",
    customizable: "Flower choice",
    description:
      "A delicate set of bookmarks made with real pressed flowers, encased in laminated paper. A thoughtful gift for any book lover.",
    sizes: ["Set of 3", "Set of 5"],
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
    category: "Gifts",
  },
  {
    id: 10,
    name: "Macramé Wall Hanging",
    price: 1199,
    tag: "Popular",
    rating: 4.8,
    reviews: 77,
    delivery: "4–6 days",
    customizable: "Size & color",
    description:
      "A handwoven macramé wall hanging that adds a boho-chic touch to any room. Made with 100% natural cotton cord and a polished wooden dowel.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    category: "Home Decor",
  },
  {
    id: 11,
    name: "Soy Wax Jar Candle",
    price: 399,
    tag: "Best Seller",
    rating: 4.9,
    reviews: 156,
    delivery: "2–4 days",
    customizable: "Scent & label",
    description:
      "A clean-burning soy wax candle in a reusable glass jar. Choose from a curated collection of calming scents. Can be personalized with a custom label.",
    sizes: ["100g", "200g", "300g"],
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    category: "Candles",
  },
  {
    id: 12,
    name: "Resin Coaster Set of 4",
    price: 699,
    tag: "Hot",
    rating: 4.8,
    reviews: 112,
    delivery: "3–5 days",
    customizable: "Colors & pattern",
    description:
      "A set of 4 handmade resin coasters, each with a unique swirl pattern. Heat-resistant, non-slip, and gorgeous enough to display even when not in use.",
    sizes: ["Set of 4"],
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    category: "Resin",
  },
  {
    id: 13,
    name: "Hand-Painted Ceramic Mug",
    price: 549,
    tag: "Trending",
    rating: 4.7,
    reviews: 68,
    delivery: "3–5 days",
    customizable: "Design & name",
    description:
      "A sturdy ceramic mug hand-painted with intricate designs. Each mug is unique and can be customized with a name or short message.",
    sizes: ["300ml", "400ml"],
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
    category: "Gifts",
  },
  {
    id: 14,
    name: "Personalized Wooden Box",
    price: 899,
    tag: "Popular",
    rating: 4.8,
    reviews: 84,
    delivery: "4–6 days",
    customizable: "Engraved name",
    description:
      "A beautiful wooden keepsake box with laser-engraved personalization. Perfect for storing jewelry, letters, or small mementos.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    category: "Frames",
  },
  {
    id: 15,
    name: "Dried Flower Bouquet",
    price: 649,
    tag: "New",
    rating: 4.6,
    reviews: 47,
    delivery: "2–4 days",
    customizable: "Flower selection",
    description:
      "A charming bouquet of carefully dried and preserved flowers. Long-lasting and maintenance-free, it makes a timeless gift or home accent.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1487530811015-780be65569bf?w=800&q=80",
    category: "Home Decor",
  },
  {
    id: 16,
    name: "Resin Ocean Wave Lamp",
    price: 2199,
    tag: "Premium",
    rating: 4.9,
    reviews: 35,
    delivery: "6–8 days",
    customizable: "Colors & size",
    description:
      "A breathtaking handcrafted resin lamp shaped like an ocean wave. Each piece is a unique work of art with LED lighting that illuminates the translucent resin beautifully.",
    sizes: ["Small", "Medium", "Large"],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    category: "Resin",
  },
  {
    id: 17,
    name: "Handmade Scented Wax Melts",
    price: 279,
    tag: "Hot",
    rating: 4.7,
    reviews: 93,
    delivery: "2–3 days",
    customizable: "Scent combo",
    description:
      "A pack of handmade scented wax melts in fun shapes and calming fragrances. Compatible with all standard wax warmers.",
    sizes: ["Pack of 6", "Pack of 12"],
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
    category: "Candles",
  },
  {
    id: 18,
    name: "Custom Couple Portrait Frame",
    price: 1399,
    tag: "Best Seller",
    rating: 4.9,
    reviews: 143,
    delivery: "5–7 days",
    customizable: "Names & date",
    description:
      "A beautifully illustrated couple portrait in a premium frame. Send us your photo and we'll create a hand-drawn style illustration — a perfect anniversary or wedding gift.",
    sizes: ["A5", "A4", "A3"],
    image: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80",
    category: "Frames",
  },
  {
    id: 19,
    name: "Terracotta Planter Set",
    price: 749,
    tag: "Trending",
    rating: 4.7,
    reviews: 66,
    delivery: "4–6 days",
    customizable: "Painted design",
    description:
      "A set of hand-painted terracotta planters in earthy tones. Each planter is individually painted with geometric or floral patterns, perfect for succulents or herbs.",
    sizes: ["Set of 2", "Set of 3"],
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
    category: "Home Decor",
  },
  {
    id: 20,
    name: "Resin Galaxy Bookends",
    price: 1899,
    tag: "Premium",
    rating: 4.9,
    reviews: 29,
    delivery: "6–8 days",
    customizable: "Galaxy colors",
    description:
      "A pair of stunning resin bookends with a deep galaxy swirl effect. Functional and artistic, these are a statement piece for any bookshelf or desk.",
    sizes: ["Standard"],
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    category: "Resin",
  },
];

export function getProductById(id: number): Product | null {
  return products.find((p) => p.id === id) ?? null;
}